// <auto-generated />
namespace Exwhyzee.ESS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class batch : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(batch));
        
        string IMigrationMetadata.Id
        {
            get { return "201903221355319_batch"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
