// <auto-generated />
namespace Exwhyzee.ESS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changes2stated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changes2stated));
        
        string IMigrationMetadata.Id
        {
            get { return "202004231414524_changes2stated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
