// <auto-generated />
namespace Exwhyzee.ESS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _65748374h7gf : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_65748374h7gf));
        
        string IMigrationMetadata.Id
        {
            get { return "202205182311441_65748374h7gf"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
